### PR TITLE
Add an option to disable waiting for notification

### PR DESCRIPTION
**Pull request by felixonmars**
When chaining with other scripts, it would be convenient if deepin-screenshot could have an option to exit immediately after taking a screenshot, without waiting for the notification window to disappear.

The option name may not be good but I guess it's still helpful to put it this way. Please let me know if you have a better idea!

Also please let me know if this isn't the appropriate way to contribute. I saw a comment (https://github.com/linuxdeepin/deepin-screenshot/pull/8#commitcomment-8380417) about using gerrit workflow to submit, but I cannot access that URL at the moment.

### CODE REVIEW

**Comment by iceleaf916** [comment]
I think this patch is good. But we can't merge the patch at github. And our gerrit workflow is at https://cr.deepin.io. Very welcome to contribute code.

**Comment by felixonmars** [comment]
@iceleaf916 I have tried to register and failed at a not found page (https://cr.deepin.io/#/register#/). I am still categoried as Anonymous and cannot seem to send patch using git review. The problem is that my contact info is missing, I cannot change it at the contact info page, and git-review fails at "You have not registered any email addresses."

Sorry it may be a silly problem since I am not familiar with gerrit, but I would really appreciate if you would tell me what I should do to get this set up. Thanks!

**Comment by snyh** [comment]
cr.deepin.io 使用的是github-plugin 来支持github.

首次登陆后进入 上面菜单栏的 github-->profile选项
https://cr.deepin.io/plugins/github-plugin-2.10-SNAPSHOT/static/account.html

然后点击导入就行了.

这个插件应该是支持导入pull request的,不过我还没测试成功.  

@fasheng 也是这边cr.deepin.io的维护者,并且也即将作为社区支持人员.  有问题欢迎多交流.

**Comment by fasheng** [comment]
类似的社区文档会尽快补齐.

刚刚已经在 irc 上给 felixonmars 发了一份简易教程. 不知道操作成功了没有?

**Comment by felixonmars** [comment]
成功提交了，多谢！ https://cr.deepin.io/#/c/7162

另外反馈一下这个插件的两个小问题：

- 未登录情况下访问这个页面会出错，而不是提示或跳回登陆
- 我的 GitHub SSH Pubkey 是 ED25519 格式，默认勾选导入会返回 Server error。

**Comment by felixonmars** [comment]
Ref: https://github.com/linuxdeepin/deepin-screenshot/commit/b3a1ca6a912da8faf3a637bb12c752d9bfd98758

**Pull request closed without merging**
